import type {
  ToolcraftComponentAcceptance,
  ToolcraftProductReadiness,
  ToolcraftTransferMode,
} from "./acceptance/types";
import { appSchema } from "./app-schema";

const persistenceSlices =
  appSchema.persistence.storage === "localStorage"
    ? appSchema.persistence.include
    : [];

export const appTransferMode: ToolcraftTransferMode = {
  mode: "new-toolcraft-app",
};

export const appProductReadiness: ToolcraftProductReadiness = {
  exportIntent: {
    image: { mode: "toolcraft-default" },
    video: { mode: "not-requested" },
  },
  interactionOwnership: [],
  mode: "product",
  productName: "Ephemera Press",
  productSummary:
    "A generator of printed ephemera on one portrait sheet across five piece families: concrete poems in four scatter arrangements, typewriter ring mandalas and stitched circles, minimal tour bills in three layouts, repeated-word texture sheets, and circular calculating wheels — two inks on paper, all deterministic per seed.",
  requestedBehavior:
    "Create a generator that can reproduce every piece family in the provided print-ephemera moodboard (concrete poetry, typewriter circle compositions, minimal tour posters, repeated-word textile sheets, and circular gauge/slide-rule wheels), driven by the same Toolcraft control-panel UI as the owner's dot-grid studio, with seeded determinism, editable text content, PNG export, and a copy-as-SVG action.",
  viewInteraction: {
    mode: "non-spatial",
    reason:
      "The product is a flat two-dimensional print composition on an artboard; there is no three-dimensional scene or model to orbit.",
  },
};

export const appAcceptance: readonly ToolcraftComponentAcceptance[] = [
  {
    automated: true,
    automatedTestName:
      "piece mode switches generators deterministically in every mode",
    browser: true,
    browserTestName:
      "browser: piece mode tabs switch poem, rings, tour, sheet, and wheel output",
    componentType: "tabs",
    evidence: "product-output",
    expectedObservable:
      "Selecting Poem, Rings, Tour, Sheet, or Wheel replaces the composed piece with that family's generator, and the selected tab persists across reloads through the values slice.",
    fixture: "seed 7 portrait sheet",
    id: "piece.mode",
    kind: "control",
    optionCoverage: "each-visible-item",
    target: "piece.mode",
    userAction: "Click the Poem, Rings, Tour, Sheet, and Wheel tabs.",
  },
  {
    automated: true,
    automatedTestName: "seed recomposes each piece deterministically per seed",
    browser: true,
    browserTestName: "browser: seed slider recomposes the piece in every mode",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Dragging the seed slider live-recomposes the piece; the same seed always sets the same sheet.",
    fixture: "seed 7 vs seed 8 compositions",
    id: "piece.seed",
    kind: "control",
    target: "piece.seed",
    userAction: "Drag the Seed slider.",
  },
  {
    automated: true,
    automatedTestName: "ink color paints the primary text and marks",
    browser: true,
    browserTestName: "browser: ink color repaints the composition",
    componentType: "color",
    evidence: "product-output",
    expectedObservable:
      "Changing Ink repaints the piece's primary text and rules in the selected color.",
    fixture: "default poem composition",
    id: "ink.primary",
    kind: "control",
    target: "ink.primary",
    userAction: "Pick a different Ink color.",
  },
  {
    automated: true,
    automatedTestName: "accent color paints dates, numbers, and stitches",
    browser: true,
    browserTestName: "browser: accent color repaints the second ink",
    componentType: "color",
    evidence: "product-output",
    expectedObservable:
      "Changing Accent repaints the piece's second-ink elements (dates, line numbers, stitches, highlights).",
    fixture: "rain poem composition with accent line numbers",
    id: "ink.accent",
    kind: "control",
    target: "ink.accent",
    userAction: "Pick a different Accent color.",
  },
  {
    automated: true,
    automatedTestName: "poem text lays out the typed words and clamps long input",
    browser: true,
    browserTestName: "browser: poem text edits recompose the scatter live",
    componentType: "code",
    evidence: "product-output",
    expectedObservable:
      "Typing into Text recomposes the poem while typing; the composed words are the typed words.",
    fixture: "default harbour poem",
    id: "poem.text",
    kind: "control",
    target: "poem.text",
    userAction: "Edit the poem in the Text editor.",
  },
  {
    automated: true,
    automatedTestName: "every poem arrangement composes a distinct scatter",
    browser: true,
    browserTestName: "browser: poem arrangement select recomposes the scatter",
    componentType: "select",
    evidence: "product-output",
    expectedObservable:
      "Choosing Drift, Rain, Gaps, or Constellation lays the same poem out as that arrangement.",
    fixture: "default harbour poem at seed 7",
    id: "poem.arrangement",
    kind: "control",
    optionCoverage: "each-visible-item",
    target: "poem.arrangement",
    userAction: "Choose each arrangement from the dropdown.",
  },
  {
    automated: true,
    automatedTestName: "poem spread widens how far words wander",
    browser: true,
    browserTestName: "browser: poem spread slider scatters the words live",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Dragging Spread widens or narrows how far words wander from the measure, live during the drag.",
    fixture: "default drift poem",
    id: "poem.spread",
    kind: "control",
    target: "poem.spread",
    userAction: "Drag the Spread slider.",
  },
  {
    automated: true,
    automatedTestName: "poem leading respaces the lines",
    browser: true,
    browserTestName: "browser: poem leading slider respaces the lines live",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "Dragging Leading respaces the poem's lines live.",
    fixture: "default drift poem",
    id: "poem.leading",
    kind: "control",
    target: "poem.leading",
    userAction: "Drag the Leading slider.",
  },
  {
    automated: true,
    automatedTestName: "poem type size rescales the set words",
    browser: true,
    browserTestName: "browser: poem type size slider rescales the words live",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "Dragging Type size rescales the set words live.",
    fixture: "default drift poem",
    id: "poem.type-size",
    kind: "control",
    target: "poem.scale",
    userAction: "Drag the Type size slider.",
  },
  {
    automated: true,
    automatedTestName: "every ring style composes a distinct ring set",
    browser: true,
    browserTestName: "browser: ring style select recomposes the rings",
    componentType: "select",
    evidence: "product-output",
    expectedObservable:
      "Choosing Typewriter, Stitched, or Orbits renders the ring set as circled words, thin stitched circles, or dotted orbits.",
    fixture: "rings mode at seed 7",
    id: "rings.style",
    kind: "control",
    optionCoverage: "each-visible-item",
    target: "rings.style",
    userAction: "Choose each ring style from the dropdown.",
  },
  {
    automated: true,
    automatedTestName: "ring words repeat around each typewriter ring",
    browser: true,
    browserTestName: "browser: ring words edits reset the circled text live",
    componentType: "text",
    evidence: "product-output",
    expectedObservable:
      "Typing into Words changes the characters set around each typewriter ring while typing.",
    fixture: "typewriter rings at seed 7",
    id: "rings.words",
    kind: "control",
    target: "rings.words",
    userAction: "Edit the Words field in Rings mode.",
  },
  {
    automated: true,
    automatedTestName: "ring count adds and removes rings",
    browser: true,
    browserTestName: "browser: ring count slider adds rings live",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "Dragging Count adds or removes rings live.",
    fixture: "rings mode at seed 7",
    id: "rings.count",
    kind: "control",
    target: "rings.count",
    userAction: "Drag the ring Count slider.",
  },
  {
    automated: true,
    automatedTestName: "ring size rescales the ring set",
    browser: true,
    browserTestName: "browser: ring size slider rescales the rings live",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "Dragging Size grows or shrinks the ring set live.",
    fixture: "rings mode at seed 7",
    id: "rings.size",
    kind: "control",
    target: "rings.size",
    userAction: "Drag the ring Size slider.",
  },
  {
    automated: true,
    automatedTestName: "ring gather pulls rings into one another",
    browser: true,
    browserTestName: "browser: ring gather slider overlaps the rings live",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Dragging Gather pulls the rings from a loose rosette into a spirograph knot live.",
    fixture: "rings mode at seed 7",
    id: "rings.gather",
    kind: "control",
    target: "rings.gather",
    userAction: "Drag the Gather slider.",
  },
  {
    automated: true,
    automatedTestName: "ring marks add accent stitches at crossings",
    browser: true,
    browserTestName: "browser: ring marks toggle stitches the crossings",
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Toggling Marks adds or removes the accent stitch dots at ring crossings and along each ring.",
    fixture: "rings mode at seed 7",
    id: "rings.marks",
    kind: "control",
    target: "rings.marks",
    userAction: "Toggle Marks in the Circles section.",
  },
  {
    automated: true,
    automatedTestName: "tour artist prints the billing line",
    browser: true,
    browserTestName: "browser: tour artist edits reset the billing live",
    componentType: "text",
    evidence: "product-output",
    expectedObservable:
      "Typing into Artist changes the printed billing line while typing.",
    fixture: "diagonal tour bill",
    id: "tour.artist",
    kind: "control",
    target: "tour.artist",
    userAction: "Edit the Artist field in Tour mode.",
  },
  {
    automated: true,
    automatedTestName:
      "tour dates parse one show per line and clamp long bills",
    browser: true,
    browserTestName: "browser: tour dates edits recompose the bill live",
    componentType: "code",
    evidence: "product-output",
    expectedObservable:
      "Editing Dates recomposes the bill while typing; each non-empty line becomes one show with date, city, and venue.",
    fixture: "default twelve-show itinerary",
    id: "tour.dates",
    kind: "control",
    target: "tour.dates",
    userAction: "Edit the Dates editor in Tour mode.",
  },
  {
    automated: true,
    automatedTestName: "every tour layout composes a distinct bill",
    browser: true,
    browserTestName: "browser: tour layout select recomposes the bill",
    componentType: "select",
    evidence: "product-output",
    expectedObservable:
      "Choosing Diagonal, Orbit, or Ledger lays the same itinerary out as a diagonal stair, a date circle, or a centred ledger.",
    fixture: "default twelve-show itinerary at seed 7",
    id: "tour.layout",
    kind: "control",
    optionCoverage: "each-visible-item",
    target: "tour.layout",
    userAction: "Choose each tour layout from the dropdown.",
  },
  {
    automated: true,
    automatedTestName: "tour leading respaces the bill",
    browser: true,
    browserTestName: "browser: tour leading slider respaces the bill live",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable: "Dragging Leading respaces the bill's lines live.",
    fixture: "diagonal tour bill",
    id: "tour.leading",
    kind: "control",
    target: "tour.leading",
    userAction: "Drag the tour Leading slider.",
  },
  {
    automated: true,
    automatedTestName: "sheet words fill the grid with the typed tokens",
    browser: true,
    browserTestName: "browser: sheet words edits refill the grid live",
    componentType: "text",
    evidence: "product-output",
    expectedObservable:
      "Typing into Words refills the texture grid with the typed tokens while typing.",
    fixture: "weave sheet at seed 7",
    id: "sheet.words",
    kind: "control",
    target: "sheet.words",
    userAction: "Edit the Words field in Sheet mode.",
  },
  {
    automated: true,
    automatedTestName: "every sheet pattern fills the grid differently",
    browser: true,
    browserTestName: "browser: sheet pattern select refills the grid",
    componentType: "select",
    evidence: "product-output",
    expectedObservable:
      "Choosing Weave, Ledger, or Patches fills the same grid as a woven texture, a numbered specimen chart, or word districts.",
    fixture: "sheet mode at seed 7",
    id: "sheet.pattern",
    kind: "control",
    optionCoverage: "each-visible-item",
    target: "sheet.pattern",
    userAction: "Choose each sheet pattern from the dropdown.",
  },
  {
    automated: true,
    automatedTestName: "sheet cell size retiles the word grid quadratically",
    browser: true,
    browserTestName: "browser: sheet cell slider retiles the grid live",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Dragging Cell size retiles the word grid live; smaller cells set more words.",
    fixture: "cell 22 vs 12 at seed 7",
    id: "sheet.cell",
    kind: "control",
    target: "sheet.cell",
    userAction: "Drag the Cell size slider.",
  },
  {
    automated: true,
    automatedTestName: "sheet void empties a fraction of slots",
    browser: true,
    browserTestName: "browser: sheet void slider empties slots live",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Dragging Void empties or refills a fraction of grid slots live.",
    fixture: "weave sheet at seed 7",
    id: "sheet.void",
    kind: "control",
    target: "sheet.void",
    userAction: "Drag the Void slider.",
  },
  {
    automated: true,
    automatedTestName:
      "sheet emphasis reweights words toward heavy and accent ink",
    browser: true,
    browserTestName: "browser: sheet emphasis slider reweights words live",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Dragging Emphasis trades regular words for heavy and accent-ink words live.",
    fixture: "weave sheet at seed 7",
    id: "sheet.emphasis",
    kind: "control",
    target: "sheet.emphasis",
    userAction: "Drag the Emphasis slider.",
  },
  {
    automated: true,
    automatedTestName:
      "every wheel instrument draws a distinct calculating face",
    browser: true,
    browserTestName: "browser: wheel instrument select redraws the face",
    componentType: "select",
    evidence: "product-output",
    expectedObservable:
      "Choosing Gauge, Knitting, Dose, or Dial draws that instrument's face: numbered gauge rings, the stitch-gauge wheel, the log-scale dose calculator, or the scribbled dial.",
    fixture: "wheel mode at seed 7",
    id: "wheel.instrument",
    kind: "control",
    optionCoverage: "each-visible-item",
    target: "wheel.instrument",
    userAction: "Choose each face from the dropdown.",
  },
  {
    automated: true,
    automatedTestName: "wheel divisions change the scale resolution",
    browser: true,
    browserTestName: "browser: wheel divisions slider re-ticks the scales live",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Dragging Divisions adds or removes ticks, numerals, and rim notches live in every instrument.",
    fixture: "divisions 36 vs 72 at seed 7",
    id: "wheel.divisions",
    kind: "control",
    target: "wheel.divisions",
    userAction: "Drag the Divisions slider.",
  },
  {
    automated: true,
    automatedTestName: "wheel rings add concentric scales",
    browser: true,
    browserTestName: "browser: wheel rings slider adds scales live",
    componentType: "slider",
    evidence: "product-output",
    expectedObservable:
      "Dragging Rings adds or removes concentric scale rings live in every instrument.",
    fixture: "wheel mode at seed 7",
    id: "wheel.rings",
    kind: "control",
    target: "wheel.rings",
    userAction: "Drag the wheel Rings slider.",
  },
  {
    automated: true,
    automatedTestName: "wheel notches cut marks into the rim",
    browser: true,
    browserTestName: "browser: wheel notches toggle cuts the rim",
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Toggling Notches adds or removes the notch marks cut into the outer rim in every instrument.",
    fixture: "wheel mode at seed 7",
    id: "wheel.notches",
    kind: "control",
    target: "wheel.notches",
    userAction: "Toggle Notches in the Instrument section.",
  },
  {
    automated: true,
    automatedTestName: "include background gates the preview background fill",
    backgroundOutputCoverage: [
      "image-transparent-when-excluded",
      "infinity-viewport-color-and-dependency",
      "preview-hidden-when-excluded",
    ],
    browser: true,
    browserTestName:
      "browser: background switch controls preview fill and PNG transparency",
    componentType: "switch",
    evidence: "product-output",
    expectedObservable:
      "Background off hides the bounded paper fill and makes PNG exports transparent; on restores the selected color and Infinity availability.",
    fixture: "default poem composition",
    id: "background.include",
    kind: "control",
    target: "export.includeBackground",
    userAction: "Toggle the Background switch in Setup.",
  },
  {
    automated: true,
    automatedTestName:
      "background color is read from state for preview and export",
    browser: true,
    browserTestName: "browser: background color repaints the paper",
    componentType: "color",
    evidence: "exported-bytes",
    expectedObservable:
      "Changing Background color changes exported paper pixels; JPG keeps an opaque background even when the Background switch is off.",
    fixture: "default poem composition",
    id: "background.color",
    kind: "control",
    target: "appearance.background",
    userAction: "Pick a different background color in Setup.",
  },
  {
    automated: true,
    automatedTestName: "image format options map to png and jpg artifacts",
    browser: true,
    browserTestName:
      "browser: image format select changes the exported file type",
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable:
      "PNG and JPG choices change the exported image MIME/file type.",
    fixture: "default composition export",
    id: "export.image-format",
    kind: "control",
    optionCoverage: ["png", "jpg"],
    target: "export.image.format",
    userAction: "Choose PNG and JPG, exporting each.",
  },
  {
    automated: true,
    automatedTestName: "image resolution options map to 2k 4k and 8k long edges",
    browser: true,
    browserTestName:
      "browser: image resolution select changes exported dimensions",
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable:
      "Resolution choices change the decoded exported image long edge to 2048/4096/8192 pixels.",
    fixture: "default composition export",
    id: "export.image-resolution",
    kind: "control",
    optionCoverage: ["2k", "4k", "8k"],
    target: "export.image.resolution",
    userAction: "Choose 2K and 8K, exporting and decoding each image.",
  },
  {
    actionCoverage: ["copy.svg"],
    automated: true,
    automatedTestName: "copy svg payload serializes the committed piece",
    browser: true,
    browserTestName: "browser: copy svg places the piece markup on the clipboard",
    componentType: "panelActions",
    evidence: "command-side-effect",
    expectedObservable:
      "Copy SVG writes a standalone SVG document of the committed piece — the same display list the preview paints — to the clipboard.",
    fixture: "default poem composition",
    id: "actions.copy-svg",
    kind: "control",
    target: "actions.output",
    userAction: "Click Copy SVG in the sticky footer and read the clipboard.",
  },
  {
    actionCoverage: ["copy.svg", "export.png"],
    automated: true,
    automatedTestName:
      "export renderer draws a deterministic frame for the export action",
    browser: true,
    browserTestName: "browser: Export PNG downloads the composed piece",
    componentType: "panelActions",
    evidence: "exported-bytes",
    expectedObservable:
      "Export PNG downloads real image bytes matching the selected format, resolution, background state, and the committed piece.",
    exportArtifactCoverage: "all-required-image-export-behavior",
    fixture: "default composition export",
    id: "actions.output",
    kind: "control",
    target: "actions.output",
    userAction:
      "Click Export PNG after choosing format and resolution; decode the artifact.",
  },
  {
    automated: true,
    automatedTestName:
      "render scale schema resolves to the canonical 1..2 slider",
    browser: true,
    browserTestName:
      "browser: render scale keeps exact backing pixels in interaction and steady states",
    componentType: "canvas",
    evidence: "rendered-pixels",
    expectedObservable:
      "The preview canvas backing equals CSS size x devicePixelRatio x selected render scale during interaction and steady state.",
    fixture: "default poem composition",
    id: "canvas.render-scale",
    kind: "runtime",
    renderScaleCoverage: {
      kind: "selected-backing-pixels",
      states: ["interaction", "steady"],
    },
    target: "canvas.renderScale",
    userAction: "Move Resolution scale and interact with the canvas.",
  },
  {
    automated: true,
    automatedTestName: "scene bounds provider fixes the portrait sheet rect",
    browser: true,
    browserTestName:
      "browser: infinity canvas removes finite sizing and restores it",
    componentType: "canvas",
    evidence: "viewport-side-effect",
    expectedObservable:
      "Infinity canvas hides finite size controls and artboard clipping; disabling restores the dormant 1080x1350 size.",
    fixture: "default composition",
    id: "canvas.infinity",
    infinityCanvasCoverage: "mode-and-restoration",
    kind: "runtime",
    target: "canvas.infinity",
    userAction: "Enable and disable Infinity canvas in Setup.",
  },
  {
    automated: true,
    automatedTestName: "infinite export scene rect is the constant sheet",
    browser: true,
    browserTestName:
      "browser: infinite export crops to the product scene bounds",
    componentType: "canvas",
    evidence: "exported-bytes",
    expectedObservable:
      "In Infinity mode, PNG export crops to the constant sheet-with-bleed product rect (1240x1510), distinct from the finite artboard.",
    fixture: "infinite mode export",
    id: "canvas.infinity-export",
    infinityCanvasCoverage: "scene-bounds-image-export",
    kind: "runtime",
    target: "canvas.infinity",
    userAction: "Enable Infinity canvas and export a PNG.",
  },
  {
    automated: true,
    automatedTestName: "default canvas size is the 1080x1350 sheet",
    browser: true,
    browserTestName: "browser: canvas width edit resizes the sheet artboard",
    componentType: "canvas",
    evidence: "command-side-effect",
    expectedObservable:
      "The artboard starts at the 1080x1350 portrait sheet; editing Canvas width changes state.canvas.size and the artboard.",
    fixture: "default composition",
    id: "canvas.default-size",
    kind: "runtime",
    target: "canvas.size.width",
    userAction: "Edit Canvas width in Setup.",
  },
  {
    automated: true,
    automatedTestName:
      "declares production reload coverage for the product schema",
    browser: true,
    browserTestName:
      "browser: app restores exact canvas, values, and panel workspace slices after reload",
    componentType: "persistence",
    evidence: "persistence-state",
    expectedObservable:
      "Canvas size and zoom, edited control values, and the moved and collapsed Controls workspace remain visibly restored after a real browser reload.",
    fixture: "product runtime persisted workspace",
    id: "persistence.reload",
    kind: "runtime",
    persistenceCoverage: "reload",
    persistenceSlices,
    target: "canvas.size.width",
    userAction:
      "Edit Canvas width and a control value, move and collapse Controls, wait for persistence, and reload the page.",
  },
];

export { appControlSectionInventory } from "./app-section-inventory";
